package reporting

import (
	"encoding/csv"
	"encoding/json"
	"fmt"
	"html/template"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// ReportConfig represents configuration for report generation
type ReportConfig struct {
	OutputDir    string
	TemplateDir  string
	PrimaryColor string
	FooterText   string
}

// ReportMetadata contains metadata for a report
type ReportMetadata struct {
	ID          string
	Title       string
	Type        string
	Format      string
	Domain      string
	GeneratedAt time.Time
}

// ReportGenerator handles report generation
type ReportGenerator struct {
	config    ReportConfig
	templates map[string]*template.Template
	pdfGen    *PDFGenerator
	emailRep  *EmailReporter
}

// ReportData holds all data needed for report generation
type ReportData struct {
	ScanResult   *ScanResult
	Metadata     ReportMetadata
	Summary      string
	IssuesByType map[string][]Issue
	TopIssues    []Issue
	Metrics      Metrics
	PrimaryColor string
	FooterText   string
	URL          string
	Issues       []Issue
}

// Metrics contains calculated metrics from scan data
type Metrics struct {
	TotalPages     int
	AvgLoadTime    float64
	TotalWords     int
	TotalImages    int
	TotalIssues    int
	CriticalIssues int
	WarningIssues  int
	InfoIssues     int
}

// NewReportGenerator creates a new report generator instance
func NewReportGenerator(config ReportConfig) (*ReportGenerator, error) {
	// Validate config
	if config.OutputDir == "" {
		config.OutputDir = "./reports"
	}
	if config.TemplateDir == "" {
		config.TemplateDir = "./templates"
	}
	if config.PrimaryColor == "" {
		config.PrimaryColor = "#4F46E5"
	}
	if config.FooterText == "" {
		config.FooterText = "Generated by AI SEO Tool"
	}

	// Create output directory if it doesn't exist
	if err := os.MkdirAll(config.OutputDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create output directory: %w", err)
	}

	rg := &ReportGenerator{
		config:    config,
		templates: make(map[string]*template.Template),
	}

	// Initialize PDF generator if needed
	pdfConfig := PDFConfig{
		OutputDir:   config.OutputDir,
		PageSize:    "A4",
		Orientation: "portrait",
		Margins:     "20mm",
	}
	
	pdfGen, err := NewPDFGenerator(pdfConfig)
	if err != nil {
		// Don't fail if PDF generation isn't available, just log
		fmt.Printf("Warning: PDF generator not available: %v\n", err)
	} else {
		rg.pdfGen = pdfGen
	}

	// Load HTML templates
	if err := rg.loadTemplates(); err != nil {
		return nil, fmt.Errorf("failed to load templates: %w", err)
	}

	return rg, nil
}

// GenerateFromScan generates a report from a single scan result
func (rg *ReportGenerator) GenerateFromScan(scan *ScanResult, reportType string, format string) (string, error) {
	if scan == nil {
		return "", fmt.Errorf("scan result cannot be nil")
	}

	// Prepare report data
	data := &ReportData{
		ScanResult: scan,
		Metadata: ReportMetadata{
			ID:          GenerateID("report"),
			Title:       fmt.Sprintf("SEO Report - %s", scan.URL),
			Type:        reportType,
			Format:      format,
			Domain:      scan.URL,
			GeneratedAt: time.Now(),
		},
		PrimaryColor: rg.config.PrimaryColor,
		FooterText:   rg.config.FooterText,
		URL:          scan.URL,
		Issues:       scan.Issues,
	}

	// Generate additional data
	data.Summary = rg.generateSummary(scan)
	data.IssuesByType = rg.groupIssuesByType(scan)
	data.TopIssues = rg.getTopIssues(scan, 10)
	data.Metrics = rg.extractMetrics(scan)

	// Generate report based on format - use string literals directly, NOT constants
	switch format {
	case "html":
		return rg.generateHTML(data, reportType)
	case "pdf":
		if rg.pdfGen == nil {
			return "", fmt.Errorf("PDF generator not available")
		}
		htmlPath, err := rg.generateHTML(data, reportType)
		if err != nil {
			return "", err
		}
		pdfPath := strings.TrimSuffix(htmlPath, ".html") + ".pdf"
		return rg.pdfGen.GenerateFromFile(htmlPath, pdfPath)
	case "json":
		return rg.generateJSON(data)
	case "csv":
		return rg.generateCSV(data)
	case "md", "markdown":
		return rg.generateMarkdown(data)
	default:
		return "", fmt.Errorf("unsupported format: %s", format)
	}
}

// GenerateFromCrawl generates a report from crawl results
func (rg *ReportGenerator) GenerateFromCrawl(crawlResults []*PageData, domain string, reportType string, format string) (string, error) {
	if len(crawlResults) == 0 {
		return "", fmt.Errorf("crawl results cannot be empty")
	}

	// Aggregate scan results
	scan := &ScanResult{
		URL:         domain,
		Pages:       crawlResults,
		Issues:      []Issue{},
		GeneratedAt: time.Now(),
	}

	// Aggregate issues from all pages
	var allIssues []Issue
	for _, page := range crawlResults {
		if page != nil {
			allIssues = append(allIssues, page.Issues...)
		}
	}
	scan.Issues = allIssues

	return rg.GenerateFromScan(scan, reportType, format)
}

// generateSummary creates an executive summary
func (rg *ReportGenerator) generateSummary(scan *ScanResult) string {
	if scan == nil {
		return ""
	}

	metrics := rg.extractMetrics(scan)
	
	var summary strings.Builder
	summary.WriteString(fmt.Sprintf("SEO Audit Summary for %s\n", scan.URL))
	summary.WriteString(fmt.Sprintf("Generated on: %s\n\n", scan.GeneratedAt.Format("2006-01-02 15:04:05")))
	summary.WriteString(fmt.Sprintf("Total Pages Analyzed: %d\n", metrics.TotalPages))
	summary.WriteString(fmt.Sprintf("Total Issues Found: %d\n", metrics.TotalIssues))
	summary.WriteString(fmt.Sprintf("- Critical: %d\n", metrics.CriticalIssues))
	summary.WriteString(fmt.Sprintf("- Warnings: %d\n", metrics.WarningIssues))
	summary.WriteString(fmt.Sprintf("- Info: %d\n", metrics.InfoIssues))
	
	if metrics.TotalPages > 0 {
		summary.WriteString(fmt.Sprintf("Average Page Load Time: %.2fs\n", metrics.AvgLoadTime))
	}
	summary.WriteString(fmt.Sprintf("Total Words Across Site: %d\n", metrics.TotalWords))
	summary.WriteString(fmt.Sprintf("Total Images: %d\n", metrics.TotalImages))

	return summary.String()
}

// groupIssuesByType groups issues by their type/category
func (rg *ReportGenerator) groupIssuesByType(scan *ScanResult) map[string][]Issue {
	if scan == nil || len(scan.Issues) == 0 {
		return make(map[string][]Issue)
	}

	grouped := make(map[string][]Issue)
	for _, issue := range scan.Issues {
		grouped[issue.Type] = append(grouped[issue.Type], issue)
	}
	return grouped
}

// extractMetrics calculates key metrics from scan data
func (rg *ReportGenerator) extractMetrics(scan *ScanResult) Metrics {
	metrics := Metrics{
		TotalPages: len(scan.Pages),
	}

	if len(scan.Pages) == 0 && len(scan.Issues) == 0 {
		return metrics
	}

	var totalLoadTime float64
	var validPages int

	for _, page := range scan.Pages {
		if page != nil {
			totalLoadTime += page.LoadTime
			metrics.TotalWords += page.WordCount
			metrics.TotalImages += page.ImageCount
			validPages++
		}
	}

	if validPages > 0 {
		metrics.AvgLoadTime = totalLoadTime / float64(validPages)
		metrics.TotalPages = validPages
	}

	// Count issues by severity
	for _, issue := range scan.Issues {
		metrics.TotalIssues++
		switch strings.ToLower(issue.Severity) {
		case "critical", "high":
			metrics.CriticalIssues++
		case "warning", "medium":
			metrics.WarningIssues++
		case "info", "low":
			metrics.InfoIssues++
		default:
			metrics.InfoIssues++
		}
	}

	return metrics
}

// getTopIssues returns the top N issues sorted by severity
func (rg *ReportGenerator) getTopIssues(scan *ScanResult, n int) []Issue {
	if scan == nil || len(scan.Issues) == 0 {
		return []Issue{}
	}

	// Sort issues by severity (critical first)
	issues := make([]Issue, len(scan.Issues))
	copy(issues, scan.Issues)
	
	sort.Slice(issues, func(i, j int) bool {
		severityOrder := map[string]int{
			"critical": 3,
			"high":     3,
			"warning":  2,
			"medium":   2,
			"info":     1,
			"low":      1,
		}
		return severityOrder[strings.ToLower(issues[i].Severity)] > 
		       severityOrder[strings.ToLower(issues[j].Severity)]
	})

	if len(issues) > n {
		return issues[:n]
	}
	return issues
}

// generateHTML renders HTML template and saves file
func (rg *ReportGenerator) generateHTML(data *ReportData, reportType string) (string, error) {
	tmpl, ok := rg.templates[reportType]
	if !ok {
		// Use summary template as fallback
		tmpl, ok = rg.templates["summary"]
		if !ok {
			return "", fmt.Errorf("no templates available")
		}
	}

	// Sanitize domain for filename
	safeDomain := strings.ReplaceAll(data.Metadata.Domain, "https://", "")
	safeDomain = strings.ReplaceAll(safeDomain, "http://", "")
	safeDomain = strings.ReplaceAll(safeDomain, "/", "_")
	safeDomain = strings.ReplaceAll(safeDomain, ".", "_")

	// Generate filename
	filename := filepath.Join(rg.config.OutputDir, 
		fmt.Sprintf("seo_report_%s_%s.html", 
			safeDomain, 
			time.Now().Format("20060102_150405")))

	// Create file
	file, err := os.Create(filename)
	if err != nil {
		return "", fmt.Errorf("failed to create HTML file: %w", err)
	}
	defer file.Close()

	// Execute template
	if err := tmpl.Execute(file, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return filename, nil
}

// generateJSON exports report as JSON
func (rg *ReportGenerator) generateJSON(data *ReportData) (string, error) {
	// Sanitize domain for filename
	safeDomain := strings.ReplaceAll(data.Metadata.Domain, "https://", "")
	safeDomain = strings.ReplaceAll(safeDomain, "http://", "")
	safeDomain = strings.ReplaceAll(safeDomain, "/", "_")
	safeDomain = strings.ReplaceAll(safeDomain, ".", "_")

	filename := filepath.Join(rg.config.OutputDir,
		fmt.Sprintf("seo_report_%s_%s.json",
			safeDomain,
			time.Now().Format("20060102_150405")))

	file, err := os.Create(filename)
	if err != nil {
		return "", fmt.Errorf("failed to create JSON file: %w", err)
	}
	defer file.Close()

	encoder := json.NewEncoder(file)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(data); err != nil {
		return "", fmt.Errorf("failed to encode JSON: %w", err)
	}

	return filename, nil
}

// generateCSV exports issues as CSV
func (rg *ReportGenerator) generateCSV(data *ReportData) (string, error) {
	// Sanitize domain for filename
	safeDomain := strings.ReplaceAll(data.Metadata.Domain, "https://", "")
	safeDomain = strings.ReplaceAll(safeDomain, "http://", "")
	safeDomain = strings.ReplaceAll(safeDomain, "/", "_")
	safeDomain = strings.ReplaceAll(safeDomain, ".", "_")

	filename := filepath.Join(rg.config.OutputDir,
		fmt.Sprintf("seo_issues_%s_%s.csv",
			safeDomain,
			time.Now().Format("20060102_150405")))

	file, err := os.Create(filename)
	if err != nil {
		return "", fmt.Errorf("failed to create CSV file: %w", err)
	}
	defer file.Close()

	writer := csv.NewWriter(file)
	defer writer.Flush()

	// Write header
	if err := writer.Write([]string{"Issue Type", "Severity", "Description", "Element", "URL", "Recommendation"}); err != nil {
		return "", fmt.Errorf("failed to write CSV header: %w", err)
	}

	// Write data
	for _, issue := range data.Issues {
		row := []string{
			issue.Type,
			issue.Severity,
			issue.Description,
			issue.Element,
			data.URL,
			issue.Recommendation,
		}
		if err := writer.Write(row); err != nil {
			return "", fmt.Errorf("failed to write CSV row: %w", err)
		}
	}

	return filename, nil
}

// generateMarkdown exports report as Markdown
func (rg *ReportGenerator) generateMarkdown(data *ReportData) (string, error) {
	// Sanitize domain for filename
	safeDomain := strings.ReplaceAll(data.Metadata.Domain, "https://", "")
	safeDomain = strings.ReplaceAll(safeDomain, "http://", "")
	safeDomain = strings.ReplaceAll(safeDomain, "/", "_")
	safeDomain = strings.ReplaceAll(safeDomain, ".", "_")

	filename := filepath.Join(rg.config.OutputDir,
		fmt.Sprintf("seo_report_%s_%s.md",
			safeDomain,
			time.Now().Format("20060102_150405")))

	file, err := os.Create(filename)
	if err != nil {
		return "", fmt.Errorf("failed to create Markdown file: %w", err)
	}
	defer file.Close()

	// Write markdown content
	var content strings.Builder
	
	content.WriteString(fmt.Sprintf("# SEO Audit Report: %s\n\n", data.Metadata.Domain))
	content.WriteString(fmt.Sprintf("**Generated:** %s\n", data.Metadata.GeneratedAt.Format("2006-01-02 15:04:05")))
	content.WriteString(fmt.Sprintf("**Report Type:** %s\n\n", data.Metadata.Type))
	content.WriteString("## Executive Summary\n\n")
	content.WriteString(data.Summary + "\n\n")
	content.WriteString("## Key Metrics\n\n")
	content.WriteString("| Metric | Value |\n")
	content.WriteString("|--------|-------|\n")
	content.WriteString(fmt.Sprintf("| Total Pages | %d |\n", data.Metrics.TotalPages))
	content.WriteString(fmt.Sprintf("| Average Load Time | %.2fs |\n", data.Metrics.AvgLoadTime))
	content.WriteString(fmt.Sprintf("| Total Words | %d |\n", data.Metrics.TotalWords))
	content.WriteString(fmt.Sprintf("| Total Images | %d |\n", data.Metrics.TotalImages))
	content.WriteString(fmt.Sprintf("| Total Issues | %d |\n\n", data.Metrics.TotalIssues))
	
	content.WriteString("## Top Issues\n\n")
	content.WriteString("| Severity | Type | Description |\n")
	content.WriteString("|----------|------|-------------|\n")

	for _, issue := range data.TopIssues {
		content.WriteString(fmt.Sprintf("| %s | %s | %s |\n",
			issue.Severity,
			issue.Type,
			issue.Description))
	}

	if _, err := file.WriteString(content.String()); err != nil {
		return "", fmt.Errorf("failed to write markdown content: %w", err)
	}

	return filename, nil
}

// loadTemplates loads HTML templates from TemplateDir or uses defaults
func (rg *ReportGenerator) loadTemplates() error {
	// Create template directory if it doesn't exist
	if err := os.MkdirAll(rg.config.TemplateDir, 0755); err != nil {
		return fmt.Errorf("failed to create template directory: %w", err)
	}

	// Define default templates
	defaultTemplates := map[string]string{
		"summary": `<!DOCTYPE html>
<html>
<head>
    <title>SEO Report - {{.Metadata.Domain}}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { 
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
            margin: 0; 
            padding: 30px; 
            background: #f9fafb;
            color: #1f2937;
            line-height: 1.5;
        }
        .container { 
            max-width: 1200px; 
            margin: 0 auto; 
            background: white; 
            border-radius: 12px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            overflow: hidden;
        }
        .header { 
            background: {{.PrimaryColor}}; 
            color: white; 
            padding: 30px; 
        }
        .header h1 { font-size: 28px; margin-bottom: 10px; }
        .header p { opacity: 0.9; font-size: 16px; }
        .content { padding: 30px; }
        .section { margin-bottom: 40px; }
        .section h2 { 
            font-size: 22px; 
            margin-bottom: 20px; 
            padding-bottom: 10px; 
            border-bottom: 2px solid #e5e7eb; 
        }
        .metrics-grid { 
            display: grid; 
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); 
            gap: 20px; 
            margin: 20px 0; 
        }
        .metric-card { 
            background: #f9fafb; 
            padding: 20px; 
            border-radius: 8px; 
            text-align: center;
            border: 1px solid #e5e7eb;
        }
        .metric-card h3 { 
            font-size: 14px; 
            color: #6b7280; 
            margin-bottom: 10px; 
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        .metric-card p { 
            font-size: 32px; 
            font-weight: bold; 
            color: {{.PrimaryColor}}; 
        }
        .severity-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 20px;
            margin: 20px 0;
        }
        .severity-card {
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            color: white;
        }
        .severity-card.critical { background: #dc2626; }
        .severity-card.warning { background: #f59e0b; }
        .severity-card.info { background: #3b82f6; }
        .severity-card h3 { font-size: 16px; margin-bottom: 10px; opacity: 0.9; }
        .severity-card p { font-size: 28px; font-weight: bold; }
        table { 
            width: 100%; 
            border-collapse: collapse; 
            margin: 20px 0; 
            background: white;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }
        th { 
            background: {{.PrimaryColor}}; 
            color: white; 
            padding: 12px; 
            text-align: left; 
            font-weight: 500;
        }
        td { 
            padding: 12px; 
            border-bottom: 1px solid #e5e7eb; 
        }
        tr:last-child td { border-bottom: none; }
        .critical { color: #dc2626; font-weight: 500; }
        .warning { color: #f59e0b; font-weight: 500; }
        .info { color: #3b82f6; font-weight: 500; }
        .footer { 
            margin-top: 40px; 
            padding: 20px 30px;
            background: #f9fafb;
            border-top: 1px solid #e5e7eb;
            font-size: 14px; 
            color: #6b7280; 
            text-align: center; 
        }
        .summary-box {
            background: #f9fafb;
            padding: 20px;
            border-radius: 8px;
            border-left: 4px solid {{.PrimaryColor}};
            font-family: monospace;
            white-space: pre-wrap;
            line-height: 1.6;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>SEO Audit Report</h1>
            <p>{{.Metadata.Domain}} | Generated: {{.Metadata.GeneratedAt.Format "January 2, 2006 15:04:05"}}</p>
        </div>
        
        <div class="content">
            <div class="section">
                <h2>Executive Summary</h2>
                <div class="summary-box">{{.Summary}}</div>
            </div>

            <div class="section">
                <h2>Key Metrics</h2>
                <div class="metrics-grid">
                    <div class="metric-card">
                        <h3>Total Pages</h3>
                        <p>{{.Metrics.TotalPages}}</p>
                    </div>
                    <div class="metric-card">
                        <h3>Avg Load Time</h3>
                        <p>{{printf "%.2f" .Metrics.AvgLoadTime}}s</p>
                    </div>
                    <div class="metric-card">
                        <h3>Total Words</h3>
                        <p>{{.Metrics.TotalWords}}</p>
                    </div>
                    <div class="metric-card">
                        <h3>Total Images</h3>
                        <p>{{.Metrics.TotalImages}}</p>
                    </div>
                </div>
            </div>

            <div class="section">
                <h2>Issues by Severity</h2>
                <div class="severity-grid">
                    <div class="severity-card critical">
                        <h3>Critical</h3>
                        <p>{{.Metrics.CriticalIssues}}</p>
                    </div>
                    <div class="severity-card warning">
                        <h3>Warnings</h3>
                        <p>{{.Metrics.WarningIssues}}</p>
                    </div>
                    <div class="severity-card info">
                        <h3>Info</h3>
                        <p>{{.Metrics.InfoIssues}}</p>
                    </div>
                </div>
            </div>

            <div class="section">
                <h2>Top Issues</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Severity</th>
                            <th>Type</th>
                            <th>Description</th>
                            <th>Element</th>
                        </tr>
                    </thead>
                    <tbody>
                        {{range .TopIssues}}
                        <tr>
                            <td class="{{.Severity}}">{{.Severity}}</td>
                            <td>{{.Type}}</td>
                            <td>{{.Description}}</td>
                            <td><code>{{.Element}}</code></td>
                        </tr>
                        {{end}}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="footer">
            {{.FooterText}} | Generated by SEO Reporting Tool
        </div>
    </div>
</body>
</html>`,
	}

	// Load or create templates
	for templateName, defaultContent := range defaultTemplates {
		templatePath := filepath.Join(rg.config.TemplateDir, templateName+".html")
		
		// Check if template file exists
		if _, err := os.Stat(templatePath); os.IsNotExist(err) {
			// Create default template
			if err := os.WriteFile(templatePath, []byte(defaultContent), 0644); err != nil {
				return fmt.Errorf("failed to create default template: %w", err)
			}
		}

		// Parse template
		tmpl, err := template.ParseFiles(templatePath)
		if err != nil {
			// If file parsing fails, use default content
			tmpl, err = template.New(templateName).Parse(defaultContent)
			if err != nil {
				return fmt.Errorf("failed to parse template %s: %w", templateName, err)
			}
		}
		rg.templates[templateName] = tmpl
	}

	return nil
}

// SetEmailReporter sets the email reporter for sending reports
func (rg *ReportGenerator) SetEmailReporter(emailRep *EmailReporter) {
	rg.emailRep = emailRep
}

// SendReport sends a generated report via email
func (rg *ReportGenerator) SendReport(to []string, subject string, reportPath string, scan *ScanResult) error {
	if rg.emailRep == nil {
		return fmt.Errorf("email reporter not configured")
	}
	if len(to) == 0 {
		return fmt.Errorf("recipients list cannot be empty")
	}
	return rg.emailRep.SendReport(to, subject, reportPath, scan)
}